# Site settings
title: danieldosen.org
email: daniel@danieldosen.org
description: "blogging on technical product development, flow, finance, economics and pop culture"
baseurl: ""
url: "http://danieldosen.org"
username: "dgdosen"

  # Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass
include: ["javascripts"]

theme: jekyll-theme-minimal